### ISSUE TITLE
Sugestões de ajustes no projeto

### ISSUE THREAD

**Issue by oliveiralex** [aglayrton/devsuperior-capitulo1-APIClients#1]
Olá, tudo bem?
Meu nome é Alexandre e estou corrigindo a sua atividade.
Seu trabalho foi aceito, parabéns. Para ficar 100%, sugiro que você faça alguns ajustes no seu projeto:

- Incluir pelo 10 registros de clientes no seu arquivo data.sql
- Está retornando um erro 500 ao tentar excluir um cliente com id inexistente. Neste caso, o mais correto seria retornar um erro 404.
- Ao tentar inserir um novo cliente (POST), está retornando um erro 500. Vi que o erro ocorre pois você incluiu uma validação para inserir um cpf válido. No entanto, sugiro que você tente tratar a imagem. O status de erro mais adequado nestes casos é o código 400 (Bad Request)

**Comment by ltecnologia-livia** [comment]
Muito obrigado, suporte super eficiente, farei as alterações.

*Obs:. Por favor, confirmar e-mail*

Atenciosamente,
*Aglayrton Julião*
*Coordenador Técnico* *d*o Eixo de Tecnologia da Informação e Comunicação
*SEDUC - Crede 08 -  EEEP Adolfo Ferreira de Sousa - INEP: 23056592*
*Telefone & Whatsapp*: (85) 99213-1997
*Skype*: aglayrton.juliao


Em dom., 25 de jul. de 2021 às 19:39, Alexandre ***@***.***>
escreveu:
